### PR TITLE
use `StorageKey` instead of String

### PR DESCRIPTION
**Pull request by safareli**
This PR makes the API less string based.

### CODE REVIEW

**Comment by joneshf** [comment]
Thanks, will look at this in a bit!

**Review by joneshf — APPROVED** [review]
Looks great! Thanks!

**Comment by safareli** [comment]
Why v3.0.2? It's a braking change so I guess next version should have been v4.0.0

**Comment by joneshf** [comment]
Sorry, I haven't published this code yet. The versions being created right now are me figuring out CI.

**Comment by joneshf** [comment]
4.0.0 is released: https://pursuit.purescript.org/packages/purescript-webstorage/4.0.0

**Comment by safareli** [comment]
Great! 🎉

**Pull request merged**
