### PR TITLE
Updates for 0.7

### PR DESCRIPTION
**Pull request by qxjit**
I made these updates while upgrading our code to 0.7. Let me know if there's anything you'd like done differently.

### CODE REVIEW

**Comment by nwolverson** [comment]
@joneshf any chance of merging this? Seems to work for me.

**Comment by beckyconning** [comment]
@joneshf what are your reservations about merging this?

**Comment by joneshf** [comment]
@beckyconning I do not have any reservations. I just don't spend my days watching github that much anymore, so things slip by.

Sorry it took so long.

**Comment by joneshf** [comment]
0.4.0 released

**Pull request merged**
