### PR TITLE
Updates for 0.11, preparing for pursuit

### PR DESCRIPTION
**Pull request by jacereda**

### CODE REVIEW

**Review by joneshf — CHANGES_REQUESTED** [review]
Thanks so much!

Can we leave the versions in `bower.json` and `package.json`? I use these when making releases. I'll merge and release after that!

**Comment by jacereda** [comment]
OK. Just curious, what do you use the versions for?

**Comment by jacereda** [comment]
I guess the effect should be renamed to WEB_STORAGE...

**Review by joneshf — APPROVED** [review]

**Comment by joneshf** [comment]
The versions are used in gulp.

When the build process changes, we can remove them.

Thanks so much for the updates!

**Comment by joneshf** [comment]
Released as https://github.com/joneshf/purescript-webstorage/releases/tag/v3.0.0

**Pull request merged**
